---
title: "Mini-Project 2"
author: "Lydia Ivanovic, Sarah Daum, Lauren Forando"
date: "2019-03-24"
output: 
  html_document:
    code_folding: hide
---
Link to Github Repository ^[git@github.com:lforando/sds192-mp2.git]

```{r setup, include=FALSE}
library(tidyverse)
library(grid)
library(gridExtra)
library(purrr)
```

```{r, eval=TRUE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, include = FALSE}
glimpse(candidates)
glimpse(house_elections)
glimpse(committees)
glimpse(contributions)
```

##Data Wrangling
```{r}
#Data Wrangling: Florida

#Overall, our goal is to look at the amount of money spent for and against opponents within both major political parties in a swing state. We chose to look at Florida because it is a well known swing state, and is large enough for us to obtain enough data regarding political contributions made.

#we created a new table named florida_elections which holds information originally stored in house_elections.
florida_elections <- house_elections %>%
  #using the filter() function, we filtered to only look at information regarding the midterm elections in Florida.
  filter(state == "FL") %>%
  #using the select() function, we selected the variables from house_elections that we wanted to move to florida_elections which included: state, candidate's name, party, number of general votes, and the general winner.
  select(state, candidate_name, party, general_votes, ge_winner)

#glimpse(florida_elections)
#glimpse(house_elections)

#Next, we want to specifiy what election year we are looking into. For this particular assignment, we analyzed the 2012 midterm elections.

#we created a second table named florida_candidates which holds information originally stored in candidates. 
florida_candidates <- candidates %>%
  #using the fiter() function, we filtered out the the state we were interested in looking at (FL), the candidate election year (2010 - 2013), and filtered out any party affiliation values that are unknown (UNK)
  filter(cand_election_yr > 2010 & cand_election_yr < 2013, cand_party_affiliation != "UNK", cand_office_state == "FL") %>%
  #using the select() function, we selected the information from candidates that we wanted to store in our new variable florida_candidates; candidate ID, candidate name, and candidate party affiliation.
  select(cand_id, cand_name, cand_party_affiliation) %>%
  rename(candidate_name = cand_name)
#glimpse(florida_candidates)


#we created a third table named florida_committees which holds information originally stored in committees. 
florida_committees <- committees %>%
  #using the select() function, we selected information from committees that we wanted to store in florida_committees: committee ID, committee name, and the name of the committee's treasurer.
  select(cmte_id, cmte_name, tres_name)
#glimpse(florida_committees)

#we created a fourth table named florida_contributions which houses information originally stored in contributions.
florida_contributions <- contributions %>%
  #using the select() function, we selected information from contributions that we wanted to move to our new variable florida_contributions.
  select(cmte_id, amndt_ind, transaction_pgi, name, transaction_amt, cand_id, tran_id, transaction_type) %>%
  #using the filter() function, we filtered out transaction types to be either infavor of a candiate (24E) or in opposition (24A).
  filter(transaction_type == "24E" | transaction_type == "24A")

#glimpse(florida_contributions)

#After creating the four new tables, we combined them together, one by one, each with a common variable.
florida_contributions_full <- florida_contributions %>%
  full_join(florida_committees, by = "cmte_id") %>%
  full_join(florida_candidates, by = "cand_id") %>%
  full_join(florida_elections, by = "candidate_name") %>%
  #once the four individual tables were combined into one main table, we used the filter() function to filter out candidate party affilitation as Republican or Democrat.
  filter(cand_party_affiliation == "REP" | cand_party_affiliation == "DEM") %>%
  #using the select() function, we selected variables deemed important from the new table containing information from the four smaller tables.
  select(cmte_id, amndt_ind, transaction_pgi, name, transaction_amt, cand_id, tran_id, transaction_type, cmte_name, tres_name, candidate_name, cand_party_affiliation) %>%
  #using the mutate() function, we added the variable trans_amount which is equal to transaction amount divided by 100,000.
  mutate(trans_amount = transaction_amt/100000)

florida_contributions_final <- na.omit(florida_contributions_full)
glimpse(florida_contributions_final)
```


```{r}
#Data Wrangling: California 

#Next, we wanted to look at the amount of money spent for and against opponents within both major political parties in a historically liberal state. We chose to look at California because it is a well known, extremely liberal state, and is large enough for us to obtain enough data regarding political contributions made. The same logic and code that was used in the data wrangling for Florida was used for California, except with different variable names, and filtering for "CA" instead of "FL". 

california_elections <- house_elections %>%
  filter(state == "CA") %>%
  select(state, candidate_name, party, general_votes, ge_winner)
#glimpse(california_elections)

california_candidates <- candidates %>%
  filter(cand_election_yr > 2010 & cand_election_yr < 2013) %>%
  filter(cand_party_affiliation != "UNK") %>%
  filter(cand_office_state == "CA") %>%
  select(cand_id, cand_name, cand_party_affiliation) %>%
  rename(candidate_name = cand_name)

#glimpse(california_candidates)

california_committees <- committees %>%
  select(cmte_id, cmte_name, tres_name)
#glimpse(california_committees)

california_contributions <- contributions %>%
  select(cmte_id, amndt_ind, transaction_pgi, name, transaction_amt, cand_id, tran_id, transaction_type) %>%
  filter(transaction_type == "24E" | transaction_type == "24A")
#glimpse(california_contributions)


california_contributions_full <- california_contributions %>%
  full_join(california_committees, by = "cmte_id") %>%
  full_join(california_candidates, by = "cand_id") %>%
  full_join(california_elections, by = "candidate_name") %>%
  filter(cand_party_affiliation == "REP" | cand_party_affiliation == "DEM") %>%
  select(cmte_id, amndt_ind, transaction_pgi, name, transaction_amt, cand_id, tran_id, transaction_type, cmte_name, tres_name, candidate_name, cand_party_affiliation) %>%
mutate(trans_amount = transaction_amt/100000)

california_contributions_final <- na.omit(california_contributions_full)
glimpse(california_contributions_final)
```



```{r}
#Data Wrangling: Texas

#Last, we wanted to look at the amount of money spent for and against opponents within both major political parties in a historically conservative state. We chose to look at Texas because it is a well known, extremely conservative state, and is large enough for us to obtain enough data regarding political contributions made. The same logic and code that was used in the data wrangling for Florida was used for Texas, except with different variable names, and filtering for "TX" instead of "FL". 


texas_elections <- house_elections %>%
  filter(state == "TX") %>%
  select(state, candidate_name, party, general_votes, ge_winner)
#glimpse(texas_elections)

texas_candidates <- candidates %>%
  filter(cand_election_yr > 2010 & cand_election_yr < 2013) %>%
  filter(cand_party_affiliation != "UNK") %>%
  filter(cand_office_state == "TX") %>%
  select(cand_id, cand_name, cand_party_affiliation) %>%
  rename(candidate_name = cand_name)
#glimpse(texas_candidates)

texas_committees <- committees %>%
  select(cmte_id, cmte_name, tres_name)
#glimpse(texas_committees)

texas_contributions <- contributions %>%
  select(cmte_id, amndt_ind, transaction_pgi, name, transaction_amt, cand_id, tran_id, transaction_type) %>%
  filter(transaction_type == "24E" | transaction_type == "24A")
#glimpse(texas_contributions)

texas_contributions_full <- texas_contributions %>%
  full_join(texas_committees, by = "cmte_id") %>%
  full_join(texas_candidates, by = "cand_id") %>%
  full_join(texas_elections, by = "candidate_name") %>%
  filter(cand_party_affiliation == "REP" | cand_party_affiliation == "DEM") %>%
  select(cmte_id, amndt_ind, transaction_pgi, name, transaction_amt, cand_id, tran_id, transaction_type, cmte_name, tres_name, candidate_name, cand_party_affiliation) %>%
mutate(trans_amount = transaction_amt/100000)

texas_contributions_final <- na.omit(texas_contributions_full)
glimpse(texas_contributions_final)
```

```{r}
#merging each of our created dataframes to one big data frame
florida_texas_merge <- merge(x = florida_contributions_final, y = texas_contributions_final, by=c("cmte_id"))
full_state_merge <- merge(x = florida_texas_merge, y = california_contributions_final, by=c("cmte_id"))
```


##*Data Graphic*

###How far does the smear campaign go?
Our data seeks to illustrate the nuance of party campaign tactics based on types of expenditure in a given state.
```{r}
contribution_type_names <- c(`24E` = "Opposing",`24A` = "In Favor")
```

```{r}
#Florida Data Graphic
florida_graphic <- ggplot(na.omit(florida_contributions_full), aes(x = cand_party_affiliation, y = trans_amount)) +
  geom_bar(stat = "identity", width=0.5, aes(fill = cand_party_affiliation)) +
  scale_fill_manual(values = c("blue", "red")) +
  facet_wrap(transaction_type~., labeller = as_labeller(contribution_type_names)) +
  ylab("Contribution Amount (in millions USD)") +
  xlab(NULL) +
  theme(panel.grid.major.x = element_blank()) +
  theme(panel.grid.minor.x = element_blank()) +
  theme(panel.grid.minor.y = element_blank()) +
  labs(title = "Florida", subtitle = "Contribution Activity in a Swing State") +
  theme(plot.title = element_text(family = "Century Gothic", size = 30, colour = 'Black', face = "bold"),
        axis.text = element_text(family = "Century Gothic", size = 20, colour = 'Black')) +
  theme(legend.position = "none")

florida_graphic
```

```{r}
#California Data Graphic
california_graphic <- ggplot(na.omit(california_contributions_full), aes(x = cand_party_affiliation, y = trans_amount)) +
  geom_bar(stat = "identity", width=0.5, aes(fill = cand_party_affiliation)) +
  scale_fill_manual(values = c("blue", "red")) +
  facet_wrap(transaction_type~., labeller = as_labeller(contribution_type_names)) +
  ylab("Contribution Amount (in millions USD)") +
  xlab("Party Affiliation") +
  labs(title = "California", subtitle = "Contribution Activity in a Blue State") +
  theme_light() +
  theme(legend.position = "none")
```


```{r}
#Texas Data Graphic
texas_graphic <- ggplot(texas_contributions_final, aes(x = cand_party_affiliation, y = trans_amount)) +
  geom_bar(stat = "identity", width=0.5, aes(fill = cand_party_affiliation)) +
  scale_fill_manual(values = c("blue", "red")) +
  facet_wrap(transaction_type~., labeller = as_labeller(contribution_type_names)) +
  ylab("Contribution Amount (in millions USD)") +
  xlab("Party Affiliation") +
  labs(title = "Texas", subtitle = "Contribution Activity in a Red State") +
  theme_light() +
  theme(legend.position = "none")
texas_graphic

#grid.arrange(florida_graphic, california_graphic, texas_graphic, nrow = 3)
```

```{r}
#Iterative Data Graphic
selected_states <- c(texas_contributions_full, florida_contributions_full, california_contributions_full)
state_graphic <- function(selected_states){
  #took out na.omit(data) becuase wasn't working in iteration
  ggplot(data = selected_states, aes(x = cand_party_affiliation, y = trans_amount)) +
  geom_bar(stat = "identity", width=0.5, aes(fill = cand_party_affiliation)) +
  scale_fill_manual(values = c("blue", "red")) +
  facet_wrap(transaction_type~., labeller = as_labeller(contribution_type_names)) +
  ylab("Contribution Amount (in millions USD)") +
  xlab(NULL) +
  theme(panel.grid.major.x = element_blank()) +
  theme(panel.grid.minor.x = element_blank()) +
  theme(panel.grid.minor.y = element_blank()) +
  #labs(title = "Florida", subtitle = "Contribution Activity in a Swing State") +
  theme(plot.title = element_text(family = "Century Gothic", size = 30, colour = 'Black', face = "bold"),
        axis.text = element_text(family = "Century Gothic", size = 20, colour = 'Black')) +
  theme(legend.position = "none")
}
#map(selected_states, state_graphic)
state_graphic(selected_states = texas_contributions_full)
state_graphic(selected_states = florida_contributions_full)
state_graphic(selected_states = california_contributions_full)
```

